
import React, { useState, useEffect } from 'react';
import { ICONS } from '../constants';

interface FAQOverlayProps {
  onClose: () => void;
}

export const FAQOverlay: React.FC<FAQOverlayProps> = ({ onClose }) => {
  const [activeTab, setActiveTab] = useState<'FAQ' | 'CONTACT'>('FAQ');
  
  // Read dynamic links
  const tutorialLink = localStorage.getItem('cinepitch_youtube_link') || "https://www.youtube.com/";
  const whatsappLink = localStorage.getItem('cinepitch_whatsapp_link') || "https://wa.me/919946704365";

  // Dynamic Content
  const [contactAddress, setContactAddress] = useState("");
  const [contactEmail, setContactEmail] = useState("");
  const [contactPhone, setContactPhone] = useState("");
  const [faqs, setFaqs] = useState<{q: string, a: string}[]>([]);

  useEffect(() => {
     setContactAddress(localStorage.getItem('cinepitch_contact_address') || "2nd floor, Kalathil Buildings,\nAkampadam, Eranhimangad.P.O.,\nNilambur, Malappuram, Kerala - 679329");
     setContactEmail(localStorage.getItem('cinepitch_contact_email') || "aicinemasuite@gmail.com");
     setContactPhone(localStorage.getItem('cinepitch_contact_phone') || "9946704365");

     const savedFaqs = localStorage.getItem('cinepitch_faqs');
     if (savedFaqs) {
        try {
           setFaqs(JSON.parse(savedFaqs));
        } catch(e) {
           console.error("Error loading FAQs");
        }
     } else {
        setFaqs([
            {
              q: "How does the AI work?",
              a: "We use advanced Gemini models (Flash 2.5 & Veo) to analyze your script/logline and generate industry-standard text, images, and video trailers."
            },
            {
              q: "Is my script secure?",
              a: "Yes. Your script is processed securely in your browser session and sent directly to Google's AI API. We do not store your intellectual property on our servers."
            },
            {
              q: "Can I use the images commercially?",
              a: "Yes. Images generated by AI generally belong to the creator (you), but checking local laws regarding AI copyright is recommended."
            },
            {
              q: "How much does it cost?",
              a: "Text generation is extremely cheap. Image generation costs ~$0.04/image. Video generation varies by duration."
            },
            {
              q: "Can I export to PDF?",
              a: "Currently, you can save your project file (.json) to resume later. A direct PDF export feature is available in the main menu."
            }
        ]);
     }
  }, []);

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="w-full max-w-2xl bg-zinc-900 border border-zinc-800 rounded-2xl shadow-2xl flex flex-col max-h-[90vh]">
        <div className="p-6 border-b border-zinc-800 flex justify-between items-center">
          <div className="flex items-center gap-4">
             <div className="bg-amber-500/10 p-2 rounded-lg text-amber-500">
               <ICONS.HelpCircle size={24} />
             </div>
             <div className="flex gap-4">
                <button 
                  onClick={() => setActiveTab('FAQ')}
                  className={`text-lg font-bold transition-colors ${activeTab === 'FAQ' ? 'text-white' : 'text-zinc-500 hover:text-zinc-300'}`}
                >
                   FAQ & Help
                </button>
                <div className="w-px bg-zinc-700 h-6"></div>
                <button 
                  onClick={() => setActiveTab('CONTACT')}
                  className={`text-lg font-bold transition-colors ${activeTab === 'CONTACT' ? 'text-white' : 'text-zinc-500 hover:text-zinc-300'}`}
                >
                   Contact Us
                </button>
             </div>
          </div>
          <button onClick={onClose} className="text-zinc-500 hover:text-white transition-colors">
            <ICONS.Minimize2 size={24} />
          </button>
        </div>
        
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
           {activeTab === 'FAQ' ? (
             <>
               {/* Video Tutorial Banner */}
               <div className="bg-gradient-to-r from-red-900/40 to-zinc-900 border border-red-900/30 rounded-xl p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
                  <div>
                    <h3 className="text-white font-bold flex items-center gap-2 mb-1 text-lg">
                      <ICONS.Youtube size={24} className="text-red-500"/> Watch Video Tutorials
                    </h3>
                    <p className="text-zinc-400 text-sm">Learn how to create pitch decks, generate characters, and more on our YouTube channel.</p>
                  </div>
                  <a 
                    href={tutorialLink} 
                    target="_blank" 
                    rel="noreferrer"
                    className="bg-red-600 hover:bg-red-500 text-white px-4 py-2 rounded-lg text-sm font-bold transition-colors flex items-center gap-2 shrink-0"
                  >
                    Visit Channel <ICONS.ExternalLink size={14}/>
                  </a>
               </div>

               {faqs.map((item, idx) => (
                 <div key={idx} className="bg-zinc-950/50 rounded-xl p-4 border border-zinc-800/50">
                   <h3 className="text-zinc-200 font-bold mb-2 flex items-start gap-2">
                     <span className="text-amber-500">Q.</span> {item.q}
                   </h3>
                   <p className="text-zinc-400 text-sm leading-relaxed pl-6 whitespace-pre-line">
                     {item.a}
                   </p>
                 </div>
               ))}
             </>
           ) : (
             <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                <div className="bg-zinc-950 rounded-xl p-8 border border-zinc-800 text-center">
                   <div className="w-16 h-16 bg-zinc-900 rounded-full flex items-center justify-center mx-auto mb-4 border border-zinc-700">
                      <ICONS.MapPin size={32} className="text-amber-500"/>
                   </div>
                   <h3 className="text-2xl font-bold text-white mb-2 cinematic-font">Pixelgraph Media</h3>
                   <p className="text-zinc-400 text-sm mb-6">Innovative AI Media Solutions</p>
                   
                   <div className="text-zinc-300 text-sm leading-relaxed whitespace-pre-line">
                      {contactAddress}
                   </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                   <a 
                     href={whatsappLink}
                     target="_blank"
                     rel="noreferrer" 
                     className="bg-zinc-950 p-4 rounded-xl border border-zinc-800 flex items-center gap-4 hover:border-green-500/50 hover:bg-zinc-900 transition-colors group cursor-pointer"
                   >
                      <div className="p-3 bg-green-900/20 text-green-500 rounded-lg group-hover:bg-green-900/30">
                         <ICONS.MessageSquare size={24}/>
                      </div>
                      <div>
                         <p className="text-xs text-zinc-500 uppercase font-bold flex items-center gap-1">
                            WhatsApp Community <ICONS.ExternalLink size={10}/>
                         </p>
                         <p className="text-white font-bold group-hover:text-green-400 transition-colors">Join Group / Chat</p>
                         <p className="text-[10px] text-zinc-500 mt-1 font-mono">{contactPhone}</p>
                      </div>
                   </a>
                   <div className="bg-zinc-950 p-4 rounded-xl border border-zinc-800 flex items-center gap-4">
                      <div className="p-3 bg-blue-900/20 text-blue-500 rounded-lg">
                         <ICONS.Box size={24}/>
                      </div>
                      <div>
                         <p className="text-xs text-zinc-500 uppercase font-bold">Email</p>
                         <a href={`mailto:${contactEmail}`} className="text-white hover:text-amber-500 transition-colors text-sm">{contactEmail}</a>
                      </div>
                   </div>
                </div>
             </div>
           )}
        </div>

        <div className="p-4 border-t border-zinc-800 bg-zinc-900 rounded-b-2xl flex justify-between items-center">
          <p className="text-xs text-zinc-500">
             {activeTab === 'FAQ' ? "Need personalized help?" : "We usually reply within 24 hours."}
          </p>
          <button 
            onClick={onClose}
            className="px-6 py-2 bg-zinc-100 text-zinc-900 rounded-md font-bold hover:bg-white"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
